name: bun-test-server-actions
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "v1.x"
      - run: bun install
      - run: yarn build
      - run: deno run --allow-net esnext/tests/server/deno-issue-reproduction.js
